"""add service, wifi, noise columns

Revision ID: 60d43c1891d2
Revises: b8e410a92df2
Create Date: 2025-09-18 20:38:22.992073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d43c1891d2'
down_revision = 'b8e410a92df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wifiQuality', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vibe', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('vibe')
        batch_op.drop_column('wifiQuality')
        batch_op.drop_column('service')

    # ### end Alembic commands ###
